# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.0 and again, edited by me :))
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

POP = None
app = None
MainWindow = None
isActive = False

popupTitle = "Break Time !"

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(348, 220)
        MainWindow.setFixedSize(MainWindow.size())
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 80, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(80, 180, 180, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 60, 81, 81))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../Icons/headphones.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 15, 260, 29))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", popupTitle))
        self.label.setText(_translate("MainWindow", "00:00:00"))
        self.pushButton.setText(_translate("MainWindow", "Hide"))
        self.label_3.setText(_translate("MainWindow", "It\'s time to take a break"))
        

one = True 
def createPopup(): #This code will NOT show the window, it only creates its object
    global POP, MainWindow, app, one
    if one:  #To be sure it creates it only one time
        app = QtWidgets.QApplication(sys.argv) 
        MainWindow = QtWidgets.QMainWindow()
        MainWindow.setWindowFlag(QtCore.Qt.WindowCloseButtonHint, False)
        POP = Ui_MainWindow()
        POP.setupUi(MainWindow)
        one = False
    

def showPopup():
    global isActive, MainWindow, POP # If the popup option is checked, then this
    try:                             # function will show it
        isActive = True             
        MainWindow.show()
        sys.exit(app.exec_())
    except:
        pass

def hidePopup():                     #Obviously this code will hide it
    global MainWindow, isActive
    try:
        MainWindow.hide()
        isActive = False
    except:
        pass
    
    
createPopup()
showPopup()
